= ISO這張照到底可以幹嘛?

很多小公司想要接政府標案時，會發現標案需求要有ISO27001的資格才能符合去標的資格。 +
這時會想到要找顧問公司，或是找公司內部的職員去上課取得證照之類的。

有在這個產業的人都知道，文件處理的工作都被認為是超級屎缺。

不過因為當年才剛轉職，我其實是很樂意嘗試不同工作，來加速自己對資訊產業的全面了解的。 +
於是我被任命為公司導入ISO27001驗證專案的主要負責人。

本人就這樣成為了眾多苦主之一，被指派負責建立制度、寫一堆文件、要想辦法讓公司從無到有通過驗證的小白 Web 仔。

我說的從無到有是指連內外網都沒分的那種。

有趣的是，公司裡無論是有經驗或沒經驗的，都沒人知道具體來說要怎麼取得。 +
上網Google就發現各種ISO27001認證課程等等等的，老闆一度還以為上完課就行了，不需要找顧問公司。

在一番調查下，我們最後當然還是找了顧問公司。

回溯記憶到當時，顧問公司的報價單中提到會輔導公司取得匡列範圍的 ISO27001 認證，輔導結束後會提供內部稽核員的證明。 +
我非常敏銳的詢問，內部稽核員的證明是什麼，我聽說還有一種要去考試才能拿到的證明，這兩種有什麼不同，能幫助我們拿到標案嗎？

顧問的回覆是考試拿的那種照，一般都是顧問才需要；小公司要做標案的話，有公司匡列範圍的 ISO 以及內部人員在輔導結束後有提供這個就可以了。

當然也是到後面我才理解，他的意思是這張是用在申請驗證公司匡列範圍的 ISO 時，用來證明內稽人員有上過課給外稽人員看的意思。

到後來，公司又要求我去上 ISO27001 主導稽核員的訓練課程。

我說，顧問公司會處理好一切，為何我們還需要去上這個課? +
因為我知道很多人有了某些照會被綁約，所以我當初很不想去上課。

公司的回覆總之需要人去上課，也沒說要綁約，以及課程竟然要5萬多，我就去上課了。

課程內容中都會寫到，課程結束後會參加一次線上考試，通過後會給原廠發的證書什麼的。

就是這個部分，是我想來寫下這篇心得的原因。

對於資訊業小白來說，光是要理解顧問輔導上課時拋出的一堆模擬兩可的名詞就很困難了。 +
要能釐清上完**「ISO27001主導稽核員訓練課程」**這堂課，並**考試**後取得的不是**「稽核員資格」**，而是**「成為稽核員的資格」**，本身就是一件很 ISO27001 的事。

沒錯，一般我們搜尋到的 ISO27001 主導稽核員的課程，上完之後只是讓你知道裡面的條文跟這套標準的稽核方法是什麼，你並不會因為這堂 5 萬多的課成為一個稽核員。

當然這也是很合理的，這麼容易就成為稽核員，這張照也會失去公信力的。

並且，要真正取得主導稽核員的正式證照，也確實需要先上完這堂課取得「成為的資格」然後再提供一系列的經歷證明，將這些經歷證明送到 IRCA 的機構審查，通過後還要每年進修、繳年費、提供每一年的稽核紀錄，才能取得那張傳說中**「可以拿去掛」**的照。

是的，回到這一切的最開始，誰沒事會想花 5 萬多去上課取得「成為的資格」呢。

就是因為這張照被在我們國家的**資安專業證照清單**中，許許多多資訊相關的標案都會要求去標案的廠商小組成員中，要有人有這張照，也就是所謂的「掛照」了。

前面說了許許多多要成為取得這張照以前要付出的錢錢和時間，而它最終的投資效益就是「拿來掛的」，因為當你的照被拿去掛時，通常都可以收取一些顧問費。

不過依據標案的嚴謹程度，也有些標案只要求「公司的 ISO27001 + 主導稽核員訓練課程結訓證明」即可。

有些標案則是沒有要求小組人員要有資格，但是標下來後到最後交付前需要找驗證公司，將「這個成果」通過 ISO27001 驗證。

以上大概就是這張照跟標案之間的關係，因為標案的要求各異，具體還是因案而異。

因此，從個人的角度來說，如果不是公司標案需要、或真心想到第三方驗證公司當稽核員或輔導顧問的話，去上這堂課甚至後續真的申請到這張照，都對個人的幫助真的都不大，畢竟每年都要花時間、金錢成本維護。

並且，如果後續你任職的角色不能參與公司的內部稽核、供應商稽核，基本上很難累積所謂的稽核紀錄，也就難以延續這張照的有效性(除非你一直都有管道給人掛)。

我也聽過有些人去上這堂課公司是沒有補助的，除非自己事先規劃好取得「成為的資格」後累積稽核實務經驗的路徑，否則完全是賠了夫人又折兵。

有感於身為一個資訊小白，自己當初懵懵懂懂地摸索這些說大不大的事情，希望透過分享能讓看到的人多一些選擇，不是在什麼都不知道的情形下被公司半推半就地推去負責這些對自己職涯不見得有幫助的事。

以上是為個人心得經歷與所見所得，如果資訊有誤，還請耐心協助勘誤，感謝閱讀。