=== 腦袋裡的水泥一直沒乾

開始認真減脂已經過了1個多月。

今天在來回運動中心的路途中，我經過一間知道了很久、但始終沒去過的地方小圖書館。

因為今天比較早出門，就決定先進去裏頭看看，結果裡面除了書種比較舊之外，環境可說是我理想的工作環境。

一小棟樓總共五層，每層面積不大，卻都有獨立的廁所和室外陽台，採光良好。

我在書庫區看了一陣子，有很多漫畫，我把交響情人夢第23集拿起來快速地翻閱回味，交響情人夢果然還是很好看，直到現在我還沒有將真人日劇系列的最終結局篇拿出來看，當年因為太過喜歡這部日劇因而捨不得看完，結果十年就這樣過去了。

接著晃到電腦工具書區，有許多跟設計模式相關的書。我拿起Javascript設計模式的書看了一下，感到很有趣。

接著去運動，結束後又走回家。

回程的路上我想起兒童時的一個回憶。

那時我畫了一張圖，是動漫風格的美少女，並驕傲地拿給同學們看。由於當時我是班上那個最喜歡畫畫的人，而同學之間沒有其他像我一樣喜愛透過展示繪畫作品來博得關注，大家也都認為我畫得很好，便紛紛要我畫他們的樣子。

我靠著這項特長找到了自己在班上的小小地位，不過也有畫膩了的時候。

有個同學似乎非常喜歡我畫的圖，每次都在我的座位旁看著我畫完再喜孜孜地收下，並鍥而不捨地要我畫完再畫。

我雖然很高興，但因為不管我怎麼畫，他都非常喜歡，不知怎地，我竟感覺自己有點像馬戲團的猴子，因此便說膩了不畫了。

他開始一再央求我繼續畫，我也一再拒絕，心裡非常疑惑和驚訝，我懷疑自己真的有畫得這麼好嗎?他有這麼喜歡我的畫嗎?跟漫畫上的圖比起來，明明就還落差一大截的呀。因此我叫他自己去看漫畫就好了。

沒想到他並沒有退縮，反而愈挫愈勇，決定用一張十元的價格跟我買我的畫。

我簡直驚呆了，從沒想過這張鉛筆畫的塗鴉可以換到十元，我心中的懷疑更加膨脹，總覺得他是不是有什麼陰謀詭計。因此我試探性地跟他說，要加到三十元，而他竟然同意了。

事到如今，我也決定遵守承諾，於是收了三十元，完成委託並交付，他也心滿意足。

然而隔天當他還想發案給我時，我拒絕了他。因為我始終無法理解他為何會願意花錢購買我的畫，始終覺得背後有什麼一連串黑暗的因果。

長到這麼大，現在的我多少可以理解當時的情況了。

一個人不需要會很多技能，因為我們永遠學不會所有的技能。對於從這麼小就懂得發案給技術人才去完成他想要結果的人，這位同學現在一定混得比我好非常多。

畢竟我是個連人家要拿錢給我做事都還感到不可置信的如此循規蹈矩的人，似乎天生就是個完美的月薪制忠實信奉者，我的腦袋真的是在裝水泥。