=== 感謝的練習

自從離職後，我從一開始每一天都在重複回想難堪的畫面，
到過年後，我開始認真思考自己的人生下一個階段，到底要專注在什麼。

我一直想一直想，也和諮商師討論。三次的免費額度用完後，我決定一個月後再來一次。

事實上我不知道為什麼我想做這件事。每次想到這個費用，就覺得對待業的我來說是一筆龐大的開銷。

但卻沒有浮現「算了吧」的想法，即使有過一次，我很刻意的去想要不要就算了呢?那個想法還是很快地就消失了。

諮商師要我找到一個方法，作為我休息的一種儀式。

人在觸摸、聞到香味這類能實際感知到某些刺激的狀態下，可以傳達訊息給大腦。

如果傳達自己喜歡、能感到放鬆的感知給大腦，那麼也就能達到放鬆的效果。
我說，我有一台小型的橢圓機，以前每天都堅持會騎三十分鐘的室內腳踏車，我想把堅持踩三十分鐘的橢圓機當作是我的儀式。諮商師說好呀，一個月後再來檢視看看執行得如何。

結束諮商的十天之中，因為我的經前焦慮，我幾乎沒有作為。
不過我接受了老公的好意，讓他把Apple Watch當作我的生日禮物。
剛開始我很掙扎，畢竟我生平從沒收過超過千元的生日禮物。
過去雖然伴侶無條件地接受了我，但我自己卻還是沒有真正無條件地接受我自己。
因此，做到這份接受，是我對自己說「沒關係」的一種方式。

結果出乎意料地令人歡喜。

因為配合手錶的充電習慣，我幾乎快要改掉懶得充電手機的壞習慣。
這件事對我來說很重要，因為我一直想要試著把注意力拉回自己身上，實體地。
並且能夠實際地觀察到自己身體的各項數值，對我的焦慮是種解脫。
只要知道，我似乎就能平靜地接受一些過去我不想直面的事情。

這段時間裡，我也一直在評估我想做的那些手術，到底要從哪開始。
最後我決定先去看鼻過敏，醫生抽血並開藥給我，我突然覺得問題變得很清晰，是有在進行某種處置的。

身體的不適過去後，我也開始嘗試建立每天踩三十分鐘橢圓機的習慣。
配合手錶的使用，我可以從活動圈圈得到明確的反饋，這讓建立習慣的過程從抽象變得具體，令人有成就感。

然後，今天我去剪頭髮了。

剪完頭髮我感到神清氣爽。
雖然下巴還是一樣地厚，但現在我能夠直視它了。

晚上，就在我決定再來做一點工作時，我發現自己又出現那種熟悉的抗拒感。
於是我開始整理東整理西，並寫下這篇日記。

也許什麼都不想做，其實意昧著腦袋裡有些乘載量已經滿了。我得把這些事、思考、感想、懊悔倒在紙上。才能騰出空間來處理新的事情。

寫到這裡，我突然意會到這確實是一種很好的方式。
畢竟那些事情，在我的腦袋裡空轉到最後，也只會被塵封在某個積水的箱子裡。
在晚上變成噩夢又把我嚇醒，最後又在某一天被我想起，重新煩惱，重新放棄。

看來寫日記記錄生活的點滴，可以是我嘗試放鬆儀式的第二個選項。

// 感謝老公買Apple Watch給我。
// 感謝VSCode可以無紙化這些繁瑣的碎語。
// 感謝中午吃的鍋貼讓我感受到美味。
// 感謝今天遇到的店員人都很好。